# Change database name, then run "rake db:create db:migrate"

defaults: &defaults
  encoding: utf-8
  username: postgres
  password: j0bb3hplop
  pool: 5
  host: 127.0.0.1
  reconnect: true
  adapter: postgresql

development:
  <<: *defaults
  database: wearefuturegov_dev

test: &test
  <<: *defaults
  database: wearefuturegov_test

cucumber:
  <<: *test